#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/sysconfig/heat-params
    owner: "root:root"
    permissions: "0644"
    content: |
      KUBE_ALLOW_PRIV="$KUBE_ALLOW_PRIV"
      FLANNEL_NETWORK_CIDR="$FLANNEL_NETWORK_CIDR"
      FLANNEL_NETWORK_SUBNETLEN="$FLANNEL_NETWORK_SUBNETLEN"
      FLANNEL_USE_VXLAN="$FLANNEL_USE_VXLAN"
      PORTAL_NETWORK_CIDR="$PORTAL_NETWORK_CIDR"
